name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    
     # Upload generated apk to the artifacts.
     
#     - uses: actions/upload-artifact@v1
#       with:
#         name: release-apk
#         path: build/app/outputs/apk/release/app-release/*.apk      
